version: '3.8'

services:
  db:
    image: postgres:16
    container_name: poll_api_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poll_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: